kind: ServiceAccount
apiVersion: v1
metadata:
  name: secret-reader
  namespace: todoapp

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: todoapp
  name: secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["list"]
---


apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-binding
  namespace: todoapp
subjects:
  - kind: ServiceAccount
    name: secret-reader
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: Role
  name: secret-reader